<a href="https://colab.research.google.com/github/Amedelokossou/Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction au calcul numérique

In [2]:
import numpy as np

In [2]:
data_trois = np.array([
   [[1, 5, 9] ,
   [8, 9, 7]] ,

   [[1, 5, 9] ,
   [8, 9, 7]] ,

   [[1, 5, 9] ,
   [8, 9, 7]]

])

In [3]:
data_trois.shape

(3, 2, 3)

In [4]:
data_trois.ndim

3

In [5]:
data_trois.size

18

In [16]:
v = np.array([1,5,9])

In [12]:
v

array([1, 5, 9])

In [17]:
v.shape

(3,)

In [13]:
v[0]

np.int64(1)

In [18]:
v[-1]

np.int64(9)

In [19]:
v[1:]

array([5, 9])

In [21]:
matrice = np.array([
    [1, 5, 9],
    [8, 6, 7]
])

In [22]:
matrice[0]

array([1, 5, 9])

In [ ]:
matrice[1, 1]

In [24]:
matrice[1]

array([8, 6, 7])

In [25]:
matrice[0][0]

np.int64(1)

In [26]:
matrice[0,0]

np.int64(1)

In [27]:
matrice[0, 2]

np.int64(9)

In [28]:
matrice[1, 1]

np.int64(6)

In [29]:
v2 = np.array([
    [1,5,9]
    ])

In [30]:
v2[0]

array([1, 5, 9])

In [32]:
v2[0, 1]

np.int64(5)

#Accèder aà des sous-tableaux d'un tableau

In [33]:
matrice

array([[1, 5, 9],
       [8, 6, 7]])

In [34]:
matrice[0, 1:]

array([5, 9])

In [35]:
matrice[1, 1:]

array([6, 7])

In [36]:
matrice[0: , 1:]

array([[5, 9],
       [6, 7]])

In [37]:
matrice[: , 1:]

array([[5, 9],
       [6, 7]])

In [8]:
matrice = np.array([
    [1, 5, 9, 4, 5],
    [8, 9, 7, 5, 0],
    [3, 2, 0, 6, 2],
    [8, 6, 7, 8, 9]
])

In [6]:
matrice.shape

(4, 5)

In [9]:
matrice[2, 3]

np.int64(6)

In [10]:
matrice[1:, 2:]

array([[7, 5, 0],
       [0, 6, 2],
       [7, 8, 9]])

In [13]:
matrice = np.arange(9).reshape((3,3))

In [14]:
matrice

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
matrice[0:2, 1:]

array([[1, 2],
       [4, 5]])

In [17]:
matrice

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
matrice[1, -1]

np.int64(5)

In [19]:
matrice[1, -1] = 9

In [27]:
matrice

array([[0, 1, 2],
       [3, 4, 9],
       [6, 7, 8]])

In [28]:
data = matrice[:2, :2]

In [30]:
data

array([[0, 1],
       [3, 4]])

In [31]:
data[0, 0] = 15

In [32]:
data

array([[15,  1],
       [ 3,  4]])

In [33]:
matrice

array([[15,  1,  2],
       [ 3,  4,  9],
       [ 6,  7,  8]])

#Comment copier alors un tableau?

In [34]:
data = matrice[:2, :2].copy()

In [35]:
data

array([[15,  1],
       [ 3,  4]])

In [37]:
data[0, 0] = 30

In [38]:
data

array([[30,  1],
       [ 3,  4]])

In [39]:
matrice

array([[15,  1,  2],
       [ 3,  4,  9],
       [ 6,  7,  8]])

#modifier la taille d'un tableau

In [47]:
x = np.random.randint(100, size=(2, 5))

In [48]:
x

array([[49, 11, 12, 76, 43],
       [81, 22, 55, 59, 94]])

In [49]:
x.shape

(2, 5)

In [50]:
x.reshape((5, 2))

array([[49, 11],
       [12, 76],
       [43, 81],
       [22, 55],
       [59, 94]])

#Concatener des tableaux

In [51]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

In [52]:
tab1 = np.concatenate([u, v])

In [53]:
tab1

array([1, 2, 3, 4, 5, 6])

In [54]:
tab = np.vstack([u, v])
tab

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
tab.shape

(2, 3)

In [56]:
tab2 = np.hstack([u, v])
tab2

array([1, 2, 3, 4, 5, 6])

#Calcul sur les tableaux avec numpy

In [57]:
nombres = list(range(2, 9))
nombres

[2, 3, 4, 5, 6, 7, 8]

In [59]:
output = np.empty(len(nombres))
output

array([ 3.81881608e-315,  0.00000000e+000,  1.11965010e-248,
        0.00000000e+000, -9.79159759e+164,  8.93366449e-311,
        0.00000000e+000])

In [61]:
for i, n in enumerate(nombres):
  output[i] = 1/n
output

array([0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
       0.14285714, 0.125     ])

In [63]:
nombres_tab = np.array(nombres)
nombres_tab

array([2, 3, 4, 5, 6, 7, 8])

In [64]:
1/nombres_tab

array([0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
       0.14285714, 0.125     ])

In [66]:
import time
nombres = list(range(2, 10000000))
output = np.empty(len(nombres))
debut = time.time()
for i, n in enumerate(nombres):
  output[i] = 1/n
fin = time.time()
print(fin - debut)

2.6638262271881104


In [67]:
debut = time.time()
1/nombres_tab
fin = time.time()
print(fin - debut)

0.0002396106719970703


#Calcul sur les tableaux avec Numpy

#Vectorisation

In [1]:
l = [5, 8, 9]
[n**2 for n in l]

[25, 64, 81]

In [4]:
np.array(l) ** 2

array([25, 64, 81])

In [5]:
np.array(l) + 1.5

array([ 6.5,  9.5, 10.5])

#Aggregation

In [6]:
l = [5, 8, 9]

In [7]:
min(l)

5

In [8]:
np.min(l)

np.int64(5)

In [9]:
np.array(l).min()

np.int64(5)

In [10]:
np.random.seed(0)
tab = np.random.randint(15, size=(5, 3))
tab

array([[12,  5,  0],
       [ 3, 11,  3],
       [ 7,  9,  3],
       [ 5,  2,  4],
       [ 7,  6,  8]])

In [13]:
np.min(tab)

np.int64(0)

In [14]:
tab.min()

np.int64(0)

In [15]:
np.min(tab, axis = 0)    #Minimum de chaque colonne


array([3, 2, 0])

In [16]:
np.min(tab, axis = 1)    #Minimum de chaque ligne

array([0, 3, 3, 2, 6])

In [17]:
np.mean(tab, axis = 1)    #Moyenne de chaque ligne

array([5.66666667, 5.66666667, 6.33333333, 3.66666667, 7.        ])

In [18]:
np.sum(tab, axis = 1)    #Somme de chaque ligne

array([17, 17, 19, 11, 21])

#Cas d'analyse des données

In [3]:
notes = np.random.randint(19, size = (10, 3))
notes

array([[ 1, 11, 12],
       [13,  9,  3],
       [16, 17,  1],
       [15, 18, 12],
       [12,  2, 12],
       [11,  3,  0],
       [15,  5, 11],
       [10,  5, 12],
       [ 0,  9, 11],
       [ 8,  0,  7]])

In [4]:
notes.shape

(10, 3)

In [9]:
moyenne_par_matière = notes.mean(axis = 0)   #La moyenne de chaque matière
moyenne_par_matière

array([10.1,  7.9,  8.1])

In [7]:
moyenne_par_etudiant = notes.mean(axis = 1)   #La moyenne de chaque étudiant
moyenne_par_etudiant

array([ 8.        ,  8.33333333, 11.33333333, 15.        ,  8.66666667,
        4.66666667, 10.33333333,  9.        ,  6.66666667,  5.        ])

#Les étidiants qui ont une moyenne supérieur à 10

In [10]:
moyenne_par_etudiant >= 10

array([False, False,  True,  True, False, False,  True, False, False,
       False])

#Combien d'étidiants qui ont une moyenne supérieur à 10

In [11]:
nbre_etudiant_ayant_moyen = np.sum(moyenne_par_etudiant >= 10)
nbre_etudiant_ayant_moyen

np.int64(3)

# Broadcasting avec Numpy

In [3]:
import numpy as np

In [11]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [22]:
matrice = np.random.randint(20, size = (3, 3))

In [16]:
a + 5

array([5, 6, 7])

In [25]:
matrice = np.random.randint(20, size = (3, 3))
matrice

array([[ 3,  7, 15],
       [ 6, 17,  5],
       [18, 15, 13]])

In [26]:
matrice + a

array([[ 3,  8, 17],
       [ 6, 18,  7],
       [18, 16, 15]])

In [28]:
np.vstack([a, a, a])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [29]:
matrice + np.vstack([a, a, a])

array([[ 3,  8, 17],
       [ 6, 18,  7],
       [18, 16, 15]])

In [8]:
n = np.random.randint(10, size = (2,3))
n

array([[4, 8, 8],
       [1, 8, 2]])

In [12]:
n.ndim

2

In [14]:
a
a.ndim

1

In [16]:
n.shape
a.shape

(3,)

In [17]:
a

array([0, 1, 2])

In [18]:
np.vstack([a, a])

array([[0, 1, 2],
       [0, 1, 2]])

In [19]:
n+a

array([[ 4,  9, 10],
       [ 1,  9,  4]])

In [21]:
m = np.arange(3).reshape((3, 1))
m

array([[0],
       [1],
       [2]])

In [42]:
h = np.random.randint(3, size=(3,))
h

array([0, 0, 2])

In [43]:
m.shape

(3, 1)

In [44]:
h.shape

(3,)

In [45]:
h.reshape((1, 3))

array([[0, 0, 2]])

In [46]:
np.vstack(([h, h, h]) )

array([[0, 0, 2],
       [0, 0, 2],
       [0, 0, 2]])

In [48]:
np.hstack(([m, m, m]) )

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [49]:
m + h

array([[0, 0, 2],
       [1, 1, 3],
       [2, 2, 4]])

#Utilité du brodcast

In [50]:
x = np.random.randint(255, size = (6, 3))
x

array([[ 15, 160, 183],
       [133,  15, 146],
       [114,  61, 136],
       [ 84, 118, 170],
       [ 61, 136,  39],
       [193, 249, 207]])

In [52]:
xmean = x.mean(axis=0)
xmean

array([100.        , 123.16666667, 146.83333333])

In [53]:
xmean.shape

(3,)

In [54]:
xstd = x.std(axis=0)
xstd

array([56.17828762, 74.10221919, 53.55812004])

In [55]:
x_centre_et_reduit = (x - xmean) / xstd
x_centre_et_reduit

array([[-1.51304007,  0.49706114,  0.67527887],
       [ 0.58741555, -1.45969538, -0.01555942],
       [ 0.2492066 , -0.83893124, -0.20227247],
       [-0.28480754, -0.06972351,  0.4325519 ],
       [-0.69421838,  0.1731842 , -2.01338907],
       [ 1.65544384,  1.69810479,  1.12339019]])

In [57]:
x_centre_et_reduit.mean()

np.float64(-9.868649107779169e-17)

In [58]:
x_centre_et_reduit.std()

np.float64(1.0)

#Plus : Fancy Indexing

In [59]:
x = np.random.randint(100, size = (5))
x

array([80, 47, 47, 68, 16])

In [60]:
x[:2] , x[2:4]

(array([80, 47]), array([47, 68]))

In [61]:
x[1:4:2]

array([47, 68])

In [63]:
x[[0, 1 , 4]]     #ceci est le fancy indexing. On indexe avec une liste des index de chaque élément

array([80, 47, 16])

In [65]:
data = np.random.randint(100, size =(6, 3))
data

array([[44, 37, 42],
       [85, 11,  5],
       [21, 89, 70],
       [19, 64, 66],
       [99, 60, 11],
       [48, 17,  4]])

In [68]:
data[:, [0,2] ]

array([[44, 42],
       [85,  5],
       [21, 70],
       [19, 66],
       [99, 11],
       [48,  4]])

In [69]:
data[:, [2,0]]

array([[42, 44],
       [ 5, 85],
       [70, 21],
       [66, 19],
       [11, 99],
       [ 4, 48]])

In [70]:
data[[2,1,4] , :]

array([[21, 89, 70],
       [85, 11,  5],
       [99, 60, 11]])

# Exercice Numpy

In [90]:
import numpy as np
# Math, Physique, SVT

x = np.array([[ 0, 13,  5],
       [ 5,  8,  2],
       [ 3,  7, 12],
       [ 2,  8,  0],
       [ 7,  4,  1]])
x

array([[ 0, 13,  5],
       [ 5,  8,  2],
       [ 3,  7, 12],
       [ 2,  8,  0],
       [ 7,  4,  1]])

In [ ]:
#x représente les notes de 5 étudiants en Maths, physique et biologie

In [77]:
#Combien de notes sont supérieur à 5 ?
notes_sup_5 = np.sum(x > 5)
notes_sup_5

np.int64(6)

In [79]:
#Quel est le nombre de notes supérieur à 8 pour chaque étudiants ?
notes_sup_8_pour_chaque_etudiant = np.sum(x > 8, axis = 1 )
notes_sup_8_pour_chaque_etudiant

array([1, 0, 1, 0, 0])

In [85]:
#Quel est le nombre d'élèves ayant au moins 2 notes supérieures à 8 ?

nbre_etud_avec_au_moins_2_note_sup_8 = np.sum(x > 8, axis = 1 )
nbre_etud_avec_au_moins_2_note_sup_8 = np.sum(nbre_etud_avec_au_moins_2_note_sup_8 >= 2)
nbre_etud_avec_au_moins_2_note_sup_8

np.int64(0)

In [86]:
#Est-ce que tous les élèves ont une note supérieur à 3 ?
nbre_etud_avec_note_sup_3 = np.sum(x > 3, axis = 1 )
nbre_etud_avec_note_sup_3

array([2, 2, 2, 1, 2])

In [87]:
#Est-ce qu'il y au moins un élève ayant au moins une note supérieur à 12 ?
nbre_etud_avec_au_moins_note_sup_12 = np.sum(x > 12 , axis = 1)
nbre_etud_avec_au_moins_note_sup_12

array([1, 0, 0, 0, 0])

In [95]:
#Quelle est la moyenne en Math et Physique de la classe si on considère uniquement les 3 élèves dont les notes apparaissent en premier ?
data = x[0:3, 0:2]
data

array([[ 0, 13],
       [ 5,  8],
       [ 3,  7]])